# Configure main menu and social menu
# [menu]
# [[menu.main]]
# name = "首页"
# url = "/"
# weight = 1
# identifier = "home"
# [menu.main.params]
# icon = "home"
# newTab = false
# [[menu.main]]
# name = "分类"
# url = "/categories/"
# weight = 2
# identifier = "categories"
# [menu.main.params]
# icon = "categories"
# newTab = false

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/codeSu97"

[social.params]
icon = "brand-github"
